package com.xyy.erp.platform.app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppMenu<M extends BaseAppMenu<M>> extends Model<M> implements IBean {
	
	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setBillType(java.lang.String billType) {
		set("billType", billType);
	}

	public java.lang.String getBillType() {
		return get("billType");
	}
	public void setMenuId(java.lang.String menuId) {
		set("menuId", menuId);
	}
	
	public java.lang.String getMenuId() {
		return get("menuId");
	}

	public void setKey(java.lang.String key) {
		set("key", key);
	}

	public java.lang.String getKey() {
		return get("key");
	}

	public void setCreatTime(java.util.Date creatTime) {
		set("creatTime", creatTime);
	}

	public java.util.Date getCreatTime() {
		return get("creatTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}
	
	public void setSortNo(java.lang.Long sortNo) {
		set("sortNo", sortNo);
	}

	public java.lang.Long getSortNo() {
		return get("sortNo");
	}
	
	public void setSrc(java.lang.String src) {
		set("src", src);
	}
	public java.lang.String getSrc() {
		return get("url");
	}
}
