CREATE TABLE `v_erp_xsck` (
  `DJBH` varchar(20) NOT NULL COMMENT '单据编号',
  `dwbh` varchar(20) DEFAULT NULL COMMENT '客户编号',
  `RQ` varchar(10) DEFAULT NULL COMMENT '订单日期',
  `RY_YWY` varchar(20) DEFAULT NULL COMMENT '业务员名称',
  `THFS` varchar(32) DEFAULT NULL COMMENT '提货方式',
  `BMID` varchar(20) DEFAULT NULL COMMENT '部门内码',
  `KHBZ` varchar(120) DEFAULT NULL COMMENT '客户备注',
  `DDLX` varchar(20) DEFAULT NULL COMMENT '订单类型(默认''正常销售'')',
  `SF_ZY` varchar(2) DEFAULT NULL COMMENT '是否中药(默认"西药")',
  `YZID` varchar(20) NOT NULL COMMENT '业主内码',
  `DJ_SORT` int(11) NOT NULL COMMENT '单据行号',
  `SPID` varchar(11) DEFAULT NULL,
  `SL` decimal(14,2) DEFAULT NULL,
  `JS` decimal(14,2) DEFAULT NULL,
  `LSS` decimal(14,2) DEFAULT NULL,
  `PH` varchar(20) DEFAULT NULL,
  `phyq` varchar(20) DEFAULT NULL,
  `SHDZ` varchar(20) DEFAULT NULL,
  `SHR` varchar(20) DEFAULT NULL,
  `LXFS` varchar(20) DEFAULT NULL,
  `IDNUMBER` varchar(18) DEFAULT NULL,
  `is_jj` varchar(2) DEFAULT NULL,
  `lastmodifytime` varchar(19) DEFAULT NULL,
  `cityname` varchar(100) DEFAULT NULL,
  `cityname2` varchar(100) DEFAULT NULL,
  `cityname3` varchar(100) DEFAULT NULL,
  `is_dshk` varchar(1) DEFAULT NULL,
  `dshkje` decimal(18,2) DEFAULT NULL,
  `shifouxiatui` varchar(2) DEFAULT '0',
  `orgId` varchar(255) DEFAULT NULL COMMENT '机构ID',
  `orgCode` varchar(255) DEFAULT NULL COMMENT '机构编码',
  `kufang` varchar(255) DEFAULT NULL COMMENT '仓库'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

