package com.xyy.erp.platform.app.model;

import com.xyy.erp.platform.app.model.base.BaseAppMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppMenu extends BaseAppMenu<AppMenu> {
	public static final AppMenu dao = new AppMenu().dao();
}
