package com.xyy.erp.platform.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setParentId(java.lang.String parentId) {
		set("parentId", parentId);
	}

	public java.lang.String getParentId() {
		return get("parentId");
	}

	public void setPermName(java.lang.String permName) {
		set("permName", permName);
	}

	public java.lang.String getPermName() {
		return get("permName");
	}

	public void setSortNo(java.lang.Integer sortNo) {
		set("sortNo", sortNo);
	}

	public java.lang.Integer getSortNo() {
		return get("sortNo");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setPermType(java.lang.Integer permType) {
		set("permType", permType);
	}

	public java.lang.Integer getPermType() {
		return get("permType");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}

	public java.lang.String getUpdator() {
		return get("updator");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
