package com.xyy.erp.platform.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDept<M extends BaseDept<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setParentId(java.lang.String parentId) {
		set("parentId", parentId);
	}

	public java.lang.String getParentId() {
		return get("parentId");
	}

	public void setDeptName(java.lang.String deptName) {
		set("deptName", deptName);
	}

	public java.lang.String getDeptName() {
		return get("deptName");
	}

	public void setSortNo(java.lang.Integer sortNo) {
		set("sortNo", sortNo);
	}

	public java.lang.Integer getSortNo() {
		return get("sortNo");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setDeptId(java.lang.String deptId) {
		set("deptId", deptId);
	}

	public java.lang.String getDeptId() {
		return get("deptId");
	}
	
	public void setZhujima(java.lang.String zhujima) {
		set("zhujima", zhujima);
	}

	public java.lang.String getZhujima() {
		return get("zhujima");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}
}
