package com.xyy.erp.platform.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataUserRelation<M extends BaseDataUserRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOrgCode(java.lang.String orgCode) {
		set("orgCode", orgCode);
	}

	public java.lang.String getOrgCode() {
		return get("orgCode");
	}
	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}
	
	public java.lang.String getOrgId() {
		return get("orgId");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

}
