package com.xyy.erp.platform.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperation<M extends BaseOperation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setModuleId(java.lang.String moduleId) {
		set("moduleId", moduleId);
	}

	public java.lang.String getModuleId() {
		return get("moduleId");
	}

	public void setModuleName(java.lang.String moduleName) {
		set("moduleName", moduleName);
	}

	public java.lang.String getModuleName() {
		return get("moduleName");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setVisible(java.lang.String visible) {
		set("visible", visible);
	}

	public java.lang.String getVisible() {
		return get("visible");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}
	
	public void setAuthority(java.lang.String state) {
		set("authority", state);
	}

	public java.lang.String getAuthority() {
		return get("authority");
	}

}
