package com.xyy.erp.platform.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWorkflowRecord<M extends BaseWorkflowRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}

	public java.lang.String getCreater() {
		return get("creater");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("createrId", createrId);
	}

	public java.lang.String getCreaterId() {
		return get("createrId");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setTi(java.lang.String ti) {
		set("ti", ti);
	}

	public java.lang.String getTi() {
		return get("ti");
	}

	public void setPi(java.lang.String pi) {
		set("pi", pi);
	}

	public java.lang.String getPi() {
		return get("pi");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setExecutor(java.lang.String executor) {
		set("executor", executor);
	}

	public java.lang.String getExecutor() {
		return get("executor");
	}

}
