package com.xyy.erp.platform.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermMenuRelation<M extends BasePermMenuRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setPermId(java.lang.String permId) {
		set("permId", permId);
	}

	public java.lang.String getPermId() {
		return get("permId");
	}

	public void setMenuId(java.lang.String menuId) {
		set("menuId", menuId);
	}

	public java.lang.String getMenuId() {
		return get("menuId");
	}

}
