package com.xyy.erp.platform.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseForceendform<M extends BaseForceendform<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	public java.lang.String getReason() {
		return get("reason");
	}

	public void setTi(java.lang.String ti) {
		set("ti", ti);
	}

	public java.lang.String getTi() {
		return get("ti");
	}

	public void setPi(java.lang.String pi) {
		set("pi", pi);
	}

	public java.lang.String getPi() {
		return get("pi");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setExecutor(java.lang.String executor) {
		set("executor", executor);
	}

	public java.lang.String getExecutor() {
		return get("executor");
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return get("orderId");
	}

	public void setOrderCode(java.lang.String orderCode) {
		set("orderCode", orderCode);
	}

	public java.lang.String getOrderCode() {
		return get("orderCode");
	}

	public void setExecutorName(java.lang.String executorName) {
		set("executorName", executorName);
	}

	public java.lang.String getExecutorName() {
		return get("executorName");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setModifier(java.lang.String modifier) {
		set("modifier", modifier);
	}

	public java.lang.String getModifier() {
		return get("modifier");
	}

	public void setModifierName(java.lang.String modifierName) {
		set("modifierName", modifierName);
	}

	public java.lang.String getModifierName() {
		return get("modifierName");
	}

}
