package com.xyy.erp.platform.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttach<M extends BaseAttach<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setPiId(java.lang.String piId) {
		set("piId", piId);
	}

	public java.lang.String getPiId() {
		return get("piId");
	}

	public void setTiId(java.lang.String tiId) {
		set("tiId", tiId);
	}

	public java.lang.String getTiId() {
		return get("tiId");
	}

	public void setDraftsId(java.lang.String draftsId) {
		set("draftsId", draftsId);
	}

	public java.lang.String getDraftsId() {
		return get("draftsId");
	}

	public void setFirstType(java.lang.String firstType) {
		set("firstType", firstType);
	}

	public java.lang.String getFirstType() {
		return get("firstType");
	}

	public void setSecondType(java.lang.String secondType) {
		set("secondType", secondType);
	}

	public java.lang.String getSecondType() {
		return get("secondType");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAttach(java.lang.String attach) {
		set("attach", attach);
	}

	public java.lang.String getAttach() {
		return get("attach");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}

	public java.lang.String getCreater() {
		return get("creater");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setRelateTable(java.lang.String relateTable) {
		set("relateTable", relateTable);
	}

	public java.lang.String getRelateTable() {
		return get("relateTable");
	}

	public void setRelateTableField(java.lang.String relateTableField) {
		set("relateTableField", relateTableField);
	}

	public java.lang.String getRelateTableField() {
		return get("relateTableField");
	}

}
