package com.xyy.erp.platform.system.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		
		arp.addMapping("tb_pd_attach", "id", Attach.class);
		arp.addMapping("tb_pd_entriessetting", "id", Entriessetting.class);
		arp.addMapping("tb_pd_forceendform", "", Forceendform.class);
		arp.addMapping("tb_pd_orderform", "", Orderform.class);
		arp.addMapping("tb_pd_suspendform", "", Suspendform.class);
	
		arp.addMapping("tb_pd_workflow_record", "id", WorkflowRecord.class);
		arp.addMapping("tb_sys_station", "id", TbSysStation.class);
		arp.addMapping("tb_sys_station_user_relation", "id", TbSysStationUserRelation.class);
		arp.addMapping("tb_sys_systems", "id", TbSysSystems.class);
	}
}

