package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseAttach;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attach extends BaseAttach<Attach> {
	public static final Attach dao = new Attach();
}
