package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseDeptRoleRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptRoleRelation extends BaseDeptRoleRelation<DeptRoleRelation> {
	public static final DeptRoleRelation dao = new DeptRoleRelation();
	
	public DeptRoleRelation() {
		this.set("id",UUIDUtil.newUUID());	
	}
}
