package com.xyy.erp.platform.system.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseDeptUserRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptUserRelation extends BaseDeptUserRelation<DeptUserRelation> {
	public static final DeptUserRelation dao = new DeptUserRelation();
	
	public DeptUserRelation(){
		set("id", UUIDUtil.newUUID());
	}
	
	/**
	 * 分页查询组织用户关系信息
	 * 
	 * @param pageNumber 页码
	 * @param pageSize 每页数量
	 * @return 分页数据
	 */
	public Page<DeptUserRelation> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "SELECT g.groupName,u.loginName ",
				"FROM tb_sys_dept_user_relation gu JOIN tb_sys_dept g ON gu.groupId = g.id JOIN tb_sys_user u ON gu.userId = u.id order by gu.id asc");
	}

	/**
	 * 添加组织用户信息
	 * @param groupUserRelation
	 * @return 
	 */
	public boolean add(DeptUserRelation groupUserRelation) {
		// TODO Auto-generated method stub
		Record record = new Record().set("id", groupUserRelation.getId()).set("deptId", groupUserRelation.getDeptId())
				.set("userId", groupUserRelation.getUserId());
		return Db.save("tb_sys_dept_user_relation", record);
		
	}
	
}
