package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseEntriessetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Entriessetting extends BaseEntriessetting<Entriessetting> {
	public static final Entriessetting dao = new Entriessetting();
}
