package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseForceendform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Forceendform extends BaseForceendform<Forceendform> {
	public static final Forceendform dao = new Forceendform();
}
