package com.xyy.erp.platform.system.model;

import java.util.ArrayList;
import java.util.List;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu();
	
	public Menu(){
		this.set("id",UUIDUtil.newUUID());	
	}
	
	private Menu parent;

	private List<Menu> childrens = new ArrayList<Menu>();

	public Menu getParent() {
		return parent;
	}

	public void setParent(Menu parent) {
		this.parent = parent;
	}

	public List<Menu> getChildrens() {
		return childrens;
	}

	public void setChildrens(List<Menu> childrens) {
		this.childrens = childrens;
	}
	
	public void addChild(Menu child){
		this.childrens.add(child);
	}
}
