package com.xyy.erp.platform.system.model;

import java.util.ArrayList;
import java.util.List;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Module extends BaseModule<Module> {
	public static final Module dao = new Module();
	
	public Module(){
		this.set("id",UUIDUtil.newUUID());	
	}
	private Module parent;

	private List<Module> childrens = new ArrayList<Module>();

	public Module getParent() {
		return parent;
	}

	public void setParent(Module parent) {
		this.parent = parent;
	}

	public List<Module> getChildrens() {
		return childrens;
	}

	public void setChildrens(List<Module> childrens) {
		this.childrens = childrens;
	}
	public void addChild(Module child){
		this.childrens.add(child);
	}
	
}
