package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseOperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operation extends BaseOperation<Operation> {
	public static final Operation dao = new Operation();
	
	public Operation(){
		this.set("id",UUIDUtil.newUUID());	
	}
}
