package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseOrderform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orderform extends BaseOrderform<Orderform> {
	public static final Orderform dao = new Orderform();
}
