package com.xyy.erp.platform.system.model;

import java.util.ArrayList;
import java.util.List;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseOrganization;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Organization extends BaseOrganization<Organization> {
	public static final Organization dao = new Organization();
	
	public Organization(){
		this.set("id",UUIDUtil.newUUID());	
	}
	
	private Organization parent;

	private List<Organization> childrens = new ArrayList<Organization>();
	
	
	public Organization getParent() {
		return parent;
	}

	public void setParent(Organization parent) {
		this.parent = parent;
	}

	public List<Organization> getChildrens() {
		return childrens;
	}

	public void setChildrens(List<Organization> childrens) {
		this.childrens = childrens;
	}
	
	public void addChild(Organization child){
		this.childrens.add(child);
	}
}
