package com.xyy.erp.platform.system.model;

import java.util.ArrayList;
import java.util.List;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	public static final Permission dao = new Permission();
	
	public Permission(){
		this.set("id",UUIDUtil.newUUID());	
	}
	
	private Permission parent;

	private List<Permission> childrens = new ArrayList<Permission>();
	
	
	public Permission getParent() {
		return parent;
	}

	public void setParent(Permission parent) {
		this.parent = parent;
	}

	public List<Permission> getChildrens() {
		return childrens;
	}

	public void setChildrens(List<Permission> childrens) {
		this.childrens = childrens;
	}
	
	public void addChild(Permission child){
		this.childrens.add(child);
	}
}
