package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BasePermMenuRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermMenuRelation extends BasePermMenuRelation<PermMenuRelation> {
	public static final PermMenuRelation dao = new PermMenuRelation();
	
	public PermMenuRelation(){
		set("id", UUIDUtil.newUUID());
	}
}
