package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseRolePermRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermRelation extends BaseRolePermRelation<RolePermRelation> {
	public static final RolePermRelation dao = new RolePermRelation();
	
	public RolePermRelation() {
		this.set("id",UUIDUtil.newUUID());	
	}
}
