package com.xyy.erp.platform.system.model;

import java.util.ArrayList;
import java.util.List;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	
	public Role(){
		this.set("id",UUIDUtil.newUUID());	
	}
	
	private Role parent;

	private List<Role> childrens = new ArrayList<Role>();
	
	
	public Role getParent() {
		return parent;
	}

	public void setParent(Role parent) {
		this.parent = parent;
	}

	public List<Role> getchildrens() {
		return childrens;
	}

	public void setchildrens(List<Role> childrens) {
		this.childrens = childrens;
	}
	
	public void addChild(Role child){
		this.childrens.add(child);
	}
}
