package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseStationUserRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StationUserRelation extends BaseStationUserRelation<StationUserRelation> {
	public static final StationUserRelation dao = new StationUserRelation();
	
	public StationUserRelation() {
		this.set("id",UUIDUtil.newUUID());	
	}
	
}
