package com.xyy.erp.platform.system.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Station extends BaseStation<Station> {
	public static final Station dao = new Station();

	public Station(){
		set("id", UUIDUtil.newUUID());
	}
	
	/**
	 * 分页查询岗位信息
	 * 
	 * @param pageNumber
	 *            页码
	 * @param pageSize
	 *            每页数量
	 * @return 分页组织数据
	 */
	public Page<Station> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, 
				"SELECT b.*,a.stationName AS parentName", 
				"FROM tb_sys_station a JOIN tb_sys_station b "
				+ "WHERE a.id = b.parentId ORDER BY id ASC");
	}

	/**
	 * 添加岗位信息
	 * @param group 
	 * @return 
	 */
	public boolean add(Station station) {
		Record record = new Record().set("id", station.getId()).set("parentId", station.getParentId())
				.set("parentName", getStationName(station)).set("stationName", station.getStationName()).set("sort", station.getSort())
				.set("state", station.getState()).set("createTime", new Date())
				.set("remark", station.getRemark());
		return Db.save("tb_sys_station", record);
	}
	/**
	 * 根据 ID查询岗位名称
	 * @param id 
	 * @return 岗位名称
	 */
	public static String getStationName(Station station){
		if(null != station.getParentId()){
			String string = Station.dao.findById(station.getParentId()).getStationName();
			System.out.println(string);
			return string;
		}
		return null;
	}
	
	private Station parent;

	private List<Station> chidrens=new ArrayList<Station>();
	
	public void addChild(Station child){
		this.chidrens.add(child);
	}
	
	public Station getParent() {
		return parent;
	}

	public void setParent(Station parent) {
		this.parent = parent;
	}

	public List<Station> getChidrens() {
		return chidrens;
	}

	public void setChidrens(List<Station> chidrens) {
		this.chidrens = chidrens;
	}
	
	
}
