package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseSuspendform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Suspendform extends BaseSuspendform<Suspendform> {
	public static final Suspendform dao = new Suspendform();
}
