package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.common.tools.UUIDUtil;
import com.xyy.erp.platform.system.model.base.BaseSystems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Systems extends BaseSystems<Systems> {
	public static final Systems dao = new Systems();
	
	public Systems(){
		this.set("id",UUIDUtil.newUUID());	
	}
}
