package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseTbSysStationUserRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSysStationUserRelation extends BaseTbSysStationUserRelation<TbSysStationUserRelation> {
	public static final TbSysStationUserRelation dao = new TbSysStationUserRelation();
}
