package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseTbSysStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSysStation extends BaseTbSysStation<TbSysStation> {
	public static final TbSysStation dao = new TbSysStation();
}
