package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseTbSysSystems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSysSystems extends BaseTbSysSystems<TbSysSystems> {
	public static final TbSysSystems dao = new TbSysSystems();
}
