package com.xyy.erp.platform.system.model;

import com.xyy.erp.platform.system.model.base.BaseWorkflowRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkflowRecord extends BaseWorkflowRecord<WorkflowRecord> {
	public static final WorkflowRecord dao = new WorkflowRecord();
}
